-- MySQL Script generated by MySQL Workbench
-- Tue Apr 10 16:50:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quiz2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz2` DEFAULT CHARACTER SET utf8 ;
USE `quiz2` ;

-- -----------------------------------------------------
-- Table `quiz2`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz2`.`class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` NCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz2`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz2`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(45) NOT NULL,
  `phone` NCHAR(11) NOT NULL,
  `password` NCHAR(64) NOT NULL,
  `class_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `student_class_fk_idx` (`class_id` ASC),
  CONSTRAINT `student_class_fk`
    FOREIGN KEY (`class_id`)
    REFERENCES `quiz2`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz2`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz2`.`question` (
  `id` INT NOT NULL,
  `title` NVARCHAR(45) NOT NULL,
  `items` JSON NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz2`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz2`.`teacher` (
  `id` INT NOT NULL,
  `name` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz2`.`teach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz2`.`teach` (
  `class_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `time_start` DATE NULL,
  `time_end` DATE NULL,
  INDEX `teach_class_fk_idx` (`class_id` ASC),
  INDEX `teach_teacher_fk_idx` (`teacher_id` ASC),
  CONSTRAINT `teach_class_fk`
    FOREIGN KEY (`class_id`)
    REFERENCES `quiz2`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teach_teacher_fk`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `quiz2`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz2`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz2`.`item` (
  `id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `item` NVARCHAR(45) NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `item_question_fk_idx` (`question_id` ASC),
  CONSTRAINT `item_question_fk`
    FOREIGN KEY (`question_id`)
    REFERENCES `quiz2`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz2`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz2`.`answer` (
  `id` INT NOT NULL,
  `time` DATE NOT NULL,
  `student_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `items` JSON NULL,
  `question_id` INT NULL,
  `score` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `answer_class_fk_idx` (`student_id` ASC),
  INDEX `answer_class_fk_idx1` (`class_id` ASC),
  INDEX `answer_teacher_fk_idx` (`teacher_id` ASC),
  INDEX `answer_question_fk_idx` (`question_id` ASC),
  CONSTRAINT `answer_student_fk`
    FOREIGN KEY (`student_id`)
    REFERENCES `quiz2`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_class_fk`
    FOREIGN KEY (`class_id`)
    REFERENCES `quiz2`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_teacher_fk`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `quiz2`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_question_fk`
    FOREIGN KEY (`question_id`)
    REFERENCES `quiz2`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
